version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: lincut_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # ВАЖНО: включаем pg_cron ещё на этапе запуска сервера
    command: >
      postgres
      -c shared_preload_libraries=pg_cron
      -c cron.database_name=lincut_db
    ports:
      - "5432:5432"
    volumes:
      # монтируем каталог с .sql-скриптами внутрь контейнера
      - ./postgres/initdb:/docker-entrypoint-initdb.d
